import { Poppins } from "next/font/google";
import "./globals.css";
import SmoothScroll from "@/component/common/SmoothScroll";
import Script from "next/script";
import ReduxProvider from "../redux/provider";
import { Toaster } from "react-hot-toast";
import Header from "@/component/Header";
import Footer from "@/component/Footer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Dignifyd Tech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} h-full antialiased`}>
      <body className="flex min-h-full flex-col font-poppins">
        <Header />

        <ReduxProvider>
          <SmoothScroll />
          {children}
        </ReduxProvider>

        <Toaster position="top-center" reverseOrder={false} />

        <Footer />

        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-VHWY59GWRT"
          strategy="afterInteractive"
        />

        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-VHWY59GWRT');
          `}
        </Script>
      </body>
    </html>
  );
}
