import { Poppins } from "next/font/google";
import "./globals.css";
import SmoothScroll from "@/component/common/SmoothScroll";
import Script from "next/script";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Dignifyd Tech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col font-poppins">
        <SmoothScroll />
        {children}
      </body>
      <Script
        src="https://www.googletagmanager.com/gtag/js?id=G-VHWY59GWRT"
        strategy="afterInteractive"
      ></Script>
      <Script id="google-analytics" strategy="afterInteractive">
        {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-VHWY59GWRT');
          `}
      </Script>
    </html>
  );
}
